### ISSUE TITLE
dask benchmark hangs on win32

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/benchmarking-public#37]
Since approximately 2024-05-04, the dask benchmark hangs indefinitely on win32, and Github Actions ultimately cancels the job for timing out.

```
[22/90] dask...
2024-05-05T05:09:08.4998637Z # 'C:\actions-runner\_work\benchmarking\benchmarking\venv\cpython3.13-6141efcf1066-compat-3c0fde653f89\Scripts\python.exe' -u 'C:\actions-runner\_work\benchmarking\benchmarking\venv\Lib\site-packages\pyperformance\data-files\benchmarks\bm_dask\run_benchmark.py' --inherit-environ PYPERFORMANCE_RUNID,PYTHON_JIT --output 'C:\WINDOWS\SERVIC~1\NETWOR~1\AppData\Local\Temp\tmph59pfj_h'
2024-05-05T10:11:04.1847490Z Benchmark suite interrupted: exit!
2024-05-05T10:11:04.1993538Z Traceback (most recent call last):
2024-05-05T10:11:04.1993975Z   File "<frozen runpy>", line 198, in _run_module_as_main
2024-05-05T10:11:04.1994410Z   File "<frozen runpy>", line 88, in _run_code
2024-05-05T10:11:04.1995596Z   File "C:\actions-runner\_work\benchmarking\benchmarking\venv\Lib\site-packages\bench_runner\__main__.py", line 34, in <module>
2024-05-05T10:11:04.2057336Z     mod.main()
2024-05-05T10:11:04.2059893Z   File "C:\actions-runner\_work\benchmarking\benchmarking\venv\Lib\site-packages\bench_runner\scripts\run_benchmarks.py", line 435, in main
2024-05-05T10:11:04.2124505Z     _main(
2024-05-05T10:11:04.2127545Z   File "C:\actions-runner\_work\benchmarking\benchmarking\venv\Lib\site-packages\bench_runner\scripts\run_benchmarks.py", line 381, in _main
2024-05-05T10:11:04.2131043Z     run_benchmarks(python, benchmarks, [], test_mode)
2024-05-05T10:11:04.2137145Z   File "C:\actions-runner\_work\benchmarking\benchmarking\venv\Lib\site-packages\bench_runner\scripts\run_benchmarks.py", line 107, in run_benchmarks
2024-05-05T10:11:04.2139725Z     subprocess.call(args)
2024-05-05T10:11:04.2141175Z   File "C:\Program Files\Python311\Lib\subprocess.py", line 391, in call
2024-05-05T10:11:04.2200063Z     return p.wait(timeout=timeout)
2024-05-05T10:11:04.2202699Z            ^^^^^^^^^^^^^^^^^^^^^^^
2024-05-05T10:11:04.2203761Z   File "C:\Program Files\Python311\Lib\subprocess.py", line 1262, in wait
2024-05-05T10:11:04.2209065Z     return self._wait(timeout=timeout)
2024-05-05T10:11:04.2210401Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-05T10:11:04.2211563Z   File "C:\Program Files\Python311\Lib\subprocess.py", line 1543, in _wait
2024-05-05T10:11:04.2223605Z     result = _winapi.WaitForSingleObject(self._handle,
2024-05-05T10:11:04.2224408Z Environment variables:
2024-05-05T10:11:04.2224880Z PYTHON_JIT=<unset>
2024-05-05T10:11:04.2228281Z RUNNING: ['C:\\actions-runner\\_work\\benchmarking\\benchmarking\\venv\\Scripts\\python.exe', '-m', 'pyperformance', 'run', '-o', WindowsPath('benchmark.json'), '--manifest', 'benchmarks.manifest', '--benchmarks', 'all,-unpack_sequence', '--python', WindowsPath('cpython/PCBuild/win32/python.exe'), '--inherit-environ', 'PYTHON_JIT']
2024-05-05T10:11:04.2231149Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-05T10:11:04.2231752Z KeyboardInterrupt
```

**Comment by mdboom** [comment]
I can reproduce this locally on current main (709ca90a00e66cea432096a7ba61aa6459d2a9a7), but also on the last known good commit on the build machine (51aefc5bf907ddffaaf0).  This makes me wonder if it's not a bug in upstream CPython, but maybe something has changed in the environment, a Windows update or something or other is blocking dask.  Just a wild theory, I'll try to gather evidence of that -- there's basically no output at all from running the dask benchmark.

**Comment by mdboom** [comment]
It's possible the *hanging* of the dask benchmark has been around a while, but was hidden by the fact that one of it's dependencies (msgpack) has had a build failure until very recently:

```
C:\actions-runner\_work\benchmarking\benchmarking\cpython\include\internal\pycore_backoff.h(47): error C7555: use of designated initializers requires at least '/std:c++20'
C:\actions-runner\_work\benchmarking\benchmarking\cpython\include\internal\pycore_backoff.h(47): error C4576: a parenthesized type followed by an initializer list is a non-standard 
```

The build failure causes the `dask` benchmark to not run (but all other benchmarks do, so this is kind of "hidden").

When the build failure goes away, it then tries to actually run the benchmark, which hangs (for an as-of-yet unknown reason).  I'm now spelunking to see when the last time it successfully ran on win32 was.

**Comment by mdboom** [comment]
So, here's the timeline, as far as I can tell:

- 2024-03-09 (17d31bf): The last time the dask benchmark worked on win32.  
- 2024-03-13 (8c094c3): The dask benchmark doesn't run, due to msgpack not compiling.
- 2024-05-06 (5f54758): The msgpack compilation error is fixed, but now there is an underlying bug that causes the benchmark to hang (only on win32).

(Note the commits above are ones that ran on the benchmark machine, they aren't bisected to the exact moment where things changed).

So at some time between 03-13 and 05-06, something in CPython changed to cause the dask benchmark to hang, but it was hidden by an underlying compilation error for msgpack.  This will make it tricky to bisect to find the cause, since the compilation fix will need to be patched in at each step.

I have already tried just upgrading dask to see if it was a bug they already found and fixed, and it doesn't fix the hang, unfortunately.

As a short term solution, we can skip the `dask` benchmark on win32, but it's probably a sign of some other underlying bug.

**Comment by gvanrossum** [comment]
- Are benchmarks running using the tier2 interpreter or the JIT?

- I notice the benchmark uses `async`/`await` (but not `asyncio`). That means we should probably scrutinize code around generators. Assuming that such changes affect genobject.c, this is the list (not sure if the first one lies within the window):
```
commit e5c699280deac076cddfef37c8af917a550f6ac3
Author: Thomas Grainger <tagrain@gmail.com>
Date:   Mon May 6 10:13:15 2024

    GH-117714: implement athrow().close() and asend().close() using throw (GH-117906)
    
    * GH-117714: replace athrow().close() and asend().close() stubs with implimentations
    
    * test athrow().close() and asend().close() raises RuntimeError
    
    * 📜🤖 Added by blurb_it.
    
    * Update Objects/genobject.c
    
    Co-authored-by: Petr Viktorin <encukou@gmail.com>
    
    ---------
    
    Co-authored-by: blurb-it[bot] <43283697+blurb-it[bot]@users.noreply.github.com>
    Co-authored-by: Petr Viktorin <encukou@gmail.com>

commit fc7e1aa3c001bbce25973261fba457035719a559
Author: Thomas Grainger <tagrain@gmail.com>
Date:   Tue Apr 30 23:44:01 2024

    GH-117881: fix athrow().throw()/asend().throw() concurrent access (GH-117882)
    
    

commit 4a1cf66c5c0afa36d7a51d5f9d3874cda10df79c
Author: Dino Viehland <dinoviehland@meta.com>
Date:   Tue Apr 30 11:38:05 2024

    gh-117657: Fix small issues with instrumentation and TSAN (#118064)
    
    Small TSAN fixups for instrumentation

commit 1f16b4ce569f222af74fcbb7b2ef98eee2398d20
Author: Irit Katriel <1055913+iritkatriel@users.noreply.github.com>
Date:   Tue Apr 30 11:32:25 2024

    gh-118272: Clear generator frame's locals when the generator is closed (#118277)
    
    Co-authored-by: Thomas Grainger <tagrain@gmail.com>

commit 7d369d471cf2b067c4d795d70b75201c48b46f5b
Author: Thomas Grainger <tagrain@gmail.com>
Date:   Wed Apr 24 05:20:19 2024

    GH-117536: GH-117894: fix athrow().throw(...) unawaited warning (GH-117851)
```

**Comment by mdboom** [comment]
> * Are benchmarks running using the tier2 interpreter or the JIT?

The benchmark hangs (on main) in both default and tier2 interpreter modes.  (I don't know about JIT).

Those commits are helpful.  Hopefully that will help to not have to bisect the whole 2 month range.

**Comment by mdboom** [comment]
I tried the parent of all of the commits above.  The earliest one 7d369d4^ (which is 975081b) still hangs.  So we probably need to bisect 17d31bf..975081b to find the first broken commit.

**Comment by mdboom** [comment]
`git bisect` says:

```
1d95451be1f3080904c00cc4c4a6cc519efdf321 is the first bad commit                                                        commit 1d95451be1f3080904c00cc4c4a6cc519efdf321                                                                         Author: Victor Stinner <vstinner@python.org>                                                                            Date:   Mon Mar 18 17:13:01 2024 +0100                                                                                                                                                                                                              gh-63207: Use GetSystemTimePreciseAsFileTime() in time.time() (#116822)                                                                                                                                                                      Doc/whatsnew/3.13.rst                              |  6 ++++                                                            .../2024-03-14-17-21-25.gh-issue-63207.LV16SL.rst  |  4 +++                                                             Python/pytime.c                                    | 38 +++++++++++++---------                                          3 files changed, 32 insertions(+), 16 deletions(-)                                                                      create mode 100644 Misc/NEWS.d/next/Library/2024-03-14-17-21-25.gh-issue-63207.LV16SL.rst                                                                                                                                 
```

I'm going to double confirm this and then move this issue to the CPython tracker.

**Comment by mdboom** [comment]
Closing this in favor of: https://github.com/python/cpython/issues/118715

**Comment by mdboom** [comment]
This has been [fixed in dask](https://github.com/dask/distributed/commit/e4a054505f1d584d920d6d1df2c419074de45d05), but until that fix ships, we still should [disable the benchmark in pyperformance](https://github.com/python/pyperformance/pull/334).

**Comment by mdboom** [comment]
@vstinner is probably in the best place to answer, but my understanding is:

1. [dask is being clever in its time handling](https://github.com/dask/distributed/blob/main/distributed/metrics.py#L46) by combining the use of `time.time()`, and `time.perf_counter()`.
2. The [CPython change that broke dask](        https://github.com/python/cpython/commit/1d95451be1f3080904c00cc4c4a6cc519efdf321) now sets the perf counter frequency from `time.time()`, using a value in a global variable, which definitely has some sort of global effect.

But I don't particularly understand these Windows APIs involved.  I think the thing to confirm is whether that change impacts anyone using `time.time()` and `time.perf_counter()` together, and whether the severity of that warrants reverting the change or just a more detailed changelog entry about the interaction.

**Comment by vstinner** [comment]
dask reads clocks 10 times and then expect some values to be equal. It was possible when the resolution was about 15.6 ms. It's no longer possible (way less likely) now that the resolution is between 100 ns and 250 ns. Each clock read gives a different timing, it's a good thing.

dask _WindowsTime is wrong and no longer needed with Python 3.13.

**Comment by gvanrossum** [comment]
Ah, so Dask was *relying* on the poor granularity of the Windows clock. Definitely their problem.
